from typing import List, Tuple

# Stenokeyboards Uni v4 - generated by resources/uni/generate.mjs.
# Maps each steno key to its physical SVG group(s); the Uni has duplicate
# physical keys (2x S-, 4x *, 2x #) so one steno key lights several caps.
# "guides" is appended every stroke; preset SVGs without finger guides simply
# lack that group and ignore it.
KEYS = {
    "S-": ["ls1", "ls2"],
    "T-": ["lt"],
    "K-": ["lk"],
    "P-": ["lp"],
    "W-": ["lw"],
    "H-": ["lh"],
    "R-": ["lr"],
    "*": ["star1", "star2", "star3", "star4"],
    "-F": ["rf"],
    "-R": ["rr"],
    "-P": ["rp"],
    "-B": ["rb"],
    "-L": ["rl"],
    "-G": ["rg"],
    "-T": ["rt"],
    "-S": ["rs"],
    "-D": ["rd"],
    "-Z": ["rz"],
    "#": ["num1", "num2"],
    "A-": ["la"],
    "O-": ["lo"],
    "-E": ["re"],
    "-U": ["ru"],
}


def convert_stroke(stroke: Tuple[str, ...], _: str) -> List[str]:
    shapes = []
    for key, gids in KEYS.items():
        pressed = key in stroke
        for gid in gids:
            shapes.append(gid if pressed else gid + "_n")
    shapes.append("guides")
    return shapes
